# bash export settings
export EDITOR=vim
export LESS="-erX"
export INPUTRC=~/.inputrc
export GREP_OPTIONS='--color=auto' GREP_COLOR='1;32'
export HISTCONTROL=erasedups
export HISTSIZE=10000
export HISTFILESIZE=10000
export HISTCONTROL=ignoredups
export HISTIGNORE="&:ls:ls *:ll:git:git status"

export PATH=~/bin:/usr/local/sbin:${PATH}
export PATH=/usr/local/bin:$PATH


export PGHOST="/var/pgsql_socket"

#Python settings
alias python="python3"

export PROJECTS=$HOME/Projects
export WORKON_HOME=$PROJECTS/envs
export PROJECT_HOME=$PROJECTS/code
export VIRTUALENVWRAPPER_PYTHON=/usr/local/bin/python3
source /usr/local/bin/virtualenvwrapper.sh
# This is to add pipenv to my path, according to these docs:
# https://docs.python-guide.org/dev/virtualenvs/
export PATH=/usr/local/bin/python3:$PATH

#Go Settings
# export GOPATH=$PROJECTS/code/go
# export GOROOT=/usr/local/opt/go/libexec
# export PATH=$PATH:$GOPATH/bin
# export PATH=$PATH:$GOROOT/bin
export GOPATH=$HOME/go
export GOROOT="$(brew --prefix golang)/libexec"
export PATH="$PATH:${GOPATH}/bin:${GOROOT}/bin"


# set customizations
set -o noclobber	# prevent overwriting files with cat.
set -o ignoreeof	# prevent Ctrl+d from automatically logging you out.

# custom aliases
alias pip="pip3"

alias emacs="emacs -nw"
alias em="emacs "
alias vi='vim'
alias ll='ls -alhG'
alias cp='cp -i'
alias mv='mv -i'
alias rm='rm -i'
alias searchcode="find ./ -name '*.py' -or -name '*.html' -or -name '*.js' -or -name '*.css' | xargs grep "
alias detabbify='sed -i -r -s -e "s/\t/ /g"'
alias du='du -sh' # disk usage is human
alias df='df -h' # disk freespace is human
alias hgrep='history | sed s/\ \ .*\ \ // | grep'
alias screen="screen -RaAU"
alias su='su -l'
alias jl='j -l'
alias jt='j -t recent'
alias jr='j -t rank'

#take me home, because I am lazy
alias home='cd ~/'

#clean up unused branches
alias git_cleanup_local='git branch --merged | grep -v "\*" | xargs -n 1 git branch -d'
alias git_cleanup_remote='git remote prune origin'

#Postgres
alias pg_start='pg_ctl -D /usr/local/var/postgres -l /usr/local/var/postgres/server.log start'
alias pg_stop='pg_ctl -D /usr/local/var/postgres stop -s -m fast'
alias pg_tail='tail -f /usr/local/var/postgres/server.log'
export PGHOST=localhost


#Load local settings
export LOCALBASH=~/.bash_local
if [ -f $LOCALBASH ];
then
    source $LOCALBASH
fi
