# Get the aliases and functions
if [ -f ~/.bashrc ]; then
    . ~/.bashrc
fi
[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*
if [ -e /Users/jackie/.nix-profile/etc/profile.d/nix.sh ]; then . /Users/jackie/.nix-profile/etc/profile.d/nix.sh; fi # added by Nix installer

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!

# Commenting, because I don't want autoset in new terminals
# __conda_setup="$('/Users/jackie/miniconda3/bin/conda' 'shell.bash' 'hook' 2> /dev/null)"
# if [ $? -eq 0 ]; then
#     eval "$__conda_setup"
# else
#     if [ -f "/Users/jackie/miniconda3/etc/profile.d/conda.sh" ]; then
#         . "/Users/jackie/miniconda3/etc/profile.d/conda.sh"
#     else
#         export PATH="/Users/jackie/miniconda3/bin:$PATH"
#     fi
# fi
# unset __conda_setup

# <<< conda initialize <<<


export PATH="$HOME/.poetry/bin:$PATH"
