# Get the aliases and functions
if [ -f ~/.bashrc ]; then
    . ~/.bashrc
fi
[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*
if [ -e /Users/jackie/.nix-profile/etc/profile.d/nix.sh ]; then . /Users/jackie/.nix-profile/etc/profile.d/nix.sh; fi # added by Nix installer
